/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry from './GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry';
import GithubComSatstreamSsUtilsOrdServerResponsesRuneTerms from './GithubComSatstreamSsUtilsOrdServerResponsesRuneTerms';

/**
 * The AllOfgithubComSatstreamSsUtilsOrdServerResponsesRuneListEntryModel1 model module.
 * @module model/AllOfgithubComSatstreamSsUtilsOrdServerResponsesRuneListEntryModel1
 * @version 1.0.19
 */
export default class AllOfgithubComSatstreamSsUtilsOrdServerResponsesRuneListEntryModel1 extends GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry {
  /**
   * Constructs a new <code>AllOfgithubComSatstreamSsUtilsOrdServerResponsesRuneListEntryModel1</code>.
   * The second element is the entry data
   * @alias module:model/AllOfgithubComSatstreamSsUtilsOrdServerResponsesRuneListEntryModel1
   * @class
   * @extends module:model/GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>AllOfgithubComSatstreamSsUtilsOrdServerResponsesRuneListEntryModel1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllOfgithubComSatstreamSsUtilsOrdServerResponsesRuneListEntryModel1} obj Optional instance to populate.
   * @return {module:model/AllOfgithubComSatstreamSsUtilsOrdServerResponsesRuneListEntryModel1} The populated <code>AllOfgithubComSatstreamSsUtilsOrdServerResponsesRuneListEntryModel1</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AllOfgithubComSatstreamSsUtilsOrdServerResponsesRuneListEntryModel1();
      GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry.constructFromObject(data, obj);
    }
    return obj;
  }
}
