/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import GithubComSatstreamSsUtilsBitcoinCliFeeHorizonEstimate from './GithubComSatstreamSsUtilsBitcoinCliFeeHorizonEstimate';

/**
 * The AllOfgithubComSatstreamSsUtilsBitcoinCliEstimateRawFeeModelShort model module.
 * @module model/AllOfgithubComSatstreamSsUtilsBitcoinCliEstimateRawFeeModelShort
 * @version 1.0.19
 */
export default class AllOfgithubComSatstreamSsUtilsBitcoinCliEstimateRawFeeModelShort extends GithubComSatstreamSsUtilsBitcoinCliFeeHorizonEstimate {
  /**
   * Constructs a new <code>AllOfgithubComSatstreamSsUtilsBitcoinCliEstimateRawFeeModelShort</code>.
   * Estimate for short time horizon
   * @alias module:model/AllOfgithubComSatstreamSsUtilsBitcoinCliEstimateRawFeeModelShort
   * @class
   * @extends module:model/GithubComSatstreamSsUtilsBitcoinCliFeeHorizonEstimate
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>AllOfgithubComSatstreamSsUtilsBitcoinCliEstimateRawFeeModelShort</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllOfgithubComSatstreamSsUtilsBitcoinCliEstimateRawFeeModelShort} obj Optional instance to populate.
   * @return {module:model/AllOfgithubComSatstreamSsUtilsBitcoinCliEstimateRawFeeModelShort} The populated <code>AllOfgithubComSatstreamSsUtilsBitcoinCliEstimateRawFeeModelShort</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AllOfgithubComSatstreamSsUtilsBitcoinCliEstimateRawFeeModelShort();
      GithubComSatstreamSsUtilsBitcoinCliFeeHorizonEstimate.constructFromObject(data, obj);
    }
    return obj;
  }
}
