/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SatstreamApi) {
      root.SatstreamApi = {};
    }
    root.SatstreamApi.BlocksGetFeesData = factory(root.SatstreamApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The BlocksGetFeesData model module.
   * @module model/BlocksGetFeesData
   * @version 1.0
   */

  /**
   * Constructs a new <code>BlocksGetFeesData</code>.
   * @alias module:model/BlocksGetFeesData
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>BlocksGetFeesData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BlocksGetFeesData} obj Optional instance to populate.
   * @return {module:model/BlocksGetFeesData} The populated <code>BlocksGetFeesData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('confirmation_blocks'))
        obj.confirmationBlocks = ApiClient.convertToType(data['confirmation_blocks'], 'Number');
      if (data.hasOwnProperty('fee_rate_in_btc'))
        obj.feeRateInBtc = ApiClient.convertToType(data['fee_rate_in_btc'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} confirmationBlocks
   */
  exports.prototype.confirmationBlocks = undefined;

  /**
   * @member {Number} feeRateInBtc
   */
  exports.prototype.feeRateInBtc = undefined;


  return exports;

}));
