/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GithubComSatstreamSsUtilsRpcBtcTx'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GithubComSatstreamSsUtilsRpcBtcTx'));
  } else {
    // Browser globals (root is window)
    if (!root.SatstreamApi) {
      root.SatstreamApi = {};
    }
    root.SatstreamApi.BlocksGetMempoolTransactions = factory(root.SatstreamApi.ApiClient, root.SatstreamApi.GithubComSatstreamSsUtilsRpcBtcTx);
  }
}(this, function(ApiClient, GithubComSatstreamSsUtilsRpcBtcTx) {
  'use strict';

  /**
   * The BlocksGetMempoolTransactions model module.
   * @module model/BlocksGetMempoolTransactions
   * @version 1.0
   */

  /**
   * Constructs a new <code>BlocksGetMempoolTransactions</code>.
   * @alias module:model/BlocksGetMempoolTransactions
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>BlocksGetMempoolTransactions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BlocksGetMempoolTransactions} obj Optional instance to populate.
   * @return {module:model/BlocksGetMempoolTransactions} The populated <code>BlocksGetMempoolTransactions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'Number');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [GithubComSatstreamSsUtilsRpcBtcTx]);
      if (data.hasOwnProperty('msg'))
        obj.msg = ApiClient.convertToType(data['msg'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} code
   */
  exports.prototype.code = undefined;

  /**
   * @member {Array.<module:model/GithubComSatstreamSsUtilsRpcBtcTx>} data
   */
  exports.prototype.data = undefined;

  /**
   * @member {String} msg
   */
  exports.prototype.msg = undefined;


  return exports;

}));
