/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CreatePSBTResponse model module.
 * @module model/CreatePSBTResponse
 * @version 1.0.38
 */
export default class CreatePSBTResponse {
  /**
   * Constructs a new <code>CreatePSBTResponse</code>.
   * @alias module:model/CreatePSBTResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreatePSBTResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreatePSBTResponse} obj Optional instance to populate.
   * @return {module:model/CreatePSBTResponse} The populated <code>CreatePSBTResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreatePSBTResponse();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'Number');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], 'String');
      if (data.hasOwnProperty('msg'))
        obj.msg = ApiClient.convertToType(data['msg'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} code
 */
CreatePSBTResponse.prototype.code = undefined;

/**
 * @member {String} data
 */
CreatePSBTResponse.prototype.data = undefined;

/**
 * @member {String} msg
 */
CreatePSBTResponse.prototype.msg = undefined;

