/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Block1 from './Block1';

/**
 * The GetBlockSummaryResponse model module.
 * @module model/GetBlockSummaryResponse
 * @version 1.0.50
 */
export default class GetBlockSummaryResponse {
  /**
   * Constructs a new <code>GetBlockSummaryResponse</code>.
   * @alias module:model/GetBlockSummaryResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetBlockSummaryResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetBlockSummaryResponse} obj Optional instance to populate.
   * @return {module:model/GetBlockSummaryResponse} The populated <code>GetBlockSummaryResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetBlockSummaryResponse();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'Number');
      if (data.hasOwnProperty('data'))
        obj.data = Block1.constructFromObject(data['data']);
      if (data.hasOwnProperty('msg'))
        obj.msg = ApiClient.convertToType(data['msg'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} code
 */
GetBlockSummaryResponse.prototype.code = undefined;

/**
 * @member {module:model/Block1} data
 */
GetBlockSummaryResponse.prototype.data = undefined;

/**
 * @member {String} msg
 */
GetBlockSummaryResponse.prototype.msg = undefined;

