/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GetNetworkHashPSResponse model module.
 * @module model/GetNetworkHashPSResponse
 * @version 1.0.44
 */
export default class GetNetworkHashPSResponse {
  /**
   * Constructs a new <code>GetNetworkHashPSResponse</code>.
   * @alias module:model/GetNetworkHashPSResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetNetworkHashPSResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetNetworkHashPSResponse} obj Optional instance to populate.
   * @return {module:model/GetNetworkHashPSResponse} The populated <code>GetNetworkHashPSResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetNetworkHashPSResponse();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'Number');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], 'Number');
      if (data.hasOwnProperty('msg'))
        obj.msg = ApiClient.convertToType(data['msg'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} code
 */
GetNetworkHashPSResponse.prototype.code = undefined;

/**
 * @member {Number} data
 */
GetNetworkHashPSResponse.prototype.data = undefined;

/**
 * @member {String} msg
 */
GetNetworkHashPSResponse.prototype.msg = undefined;

