/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData model module.
 * @module model/GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData
 * @version 1.0.19
 */
export default class GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData {
  /**
   * Constructs a new <code>GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData</code>.
   * @alias module:model/GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData} obj Optional instance to populate.
   * @return {module:model/GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData} The populated <code>GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData();
      if (data.hasOwnProperty('pubkeys'))
        obj.pubkeys = ApiClient.convertToType(data['pubkeys'], ['String']);
      if (data.hasOwnProperty('redeemscript'))
        obj.redeemscript = ApiClient.convertToType(data['redeemscript'], 'String');
      if (data.hasOwnProperty('signatures'))
        obj.signatures = ApiClient.convertToType(data['signatures'], ['String']);
      if (data.hasOwnProperty('witnessscript'))
        obj.witnessscript = ApiClient.convertToType(data['witnessscript'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} pubkeys
 */
GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData.prototype.pubkeys = undefined;

/**
 * @member {String} redeemscript
 */
GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData.prototype.redeemscript = undefined;

/**
 * @member {Array.<String>} signatures
 */
GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData.prototype.signatures = undefined;

/**
 * @member {String} witnessscript
 */
GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData.prototype.witnessscript = undefined;

