/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTInput model module.
 * @module model/GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTInput
 * @version 1.0.19
 */
export default class GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTInput {
  /**
   * Constructs a new <code>GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTInput</code>.
   * @alias module:model/GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTInput
   * @class
   * @param txid {String} The transaction id
   * @param vout {Number} The output number
   */
  constructor(txid, vout) {
    this.txid = txid;
    this.vout = vout;
  }

  /**
   * Constructs a <code>GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTInput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTInput} obj Optional instance to populate.
   * @return {module:model/GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTInput} The populated <code>GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTInput</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTInput();
      if (data.hasOwnProperty('sequence'))
        obj.sequence = ApiClient.convertToType(data['sequence'], 'Number');
      if (data.hasOwnProperty('txid'))
        obj.txid = ApiClient.convertToType(data['txid'], 'String');
      if (data.hasOwnProperty('vout'))
        obj.vout = ApiClient.convertToType(data['vout'], 'Number');
    }
    return obj;
  }
}

/**
 * The sequence number Optional, default depends on the value of the 'replaceable' and 'locktime' arguments
 * @member {Number} sequence
 */
GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTInput.prototype.sequence = undefined;

/**
 * The transaction id
 * @member {String} txid
 */
GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTInput.prototype.txid = undefined;

/**
 * The output number
 * @member {Number} vout
 */
GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTInput.prototype.vout = undefined;

