/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BigInt'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BigInt'));
  } else {
    // Browser globals (root is window)
    if (!root.SatstreamApi) {
      root.SatstreamApi = {};
    }
    root.SatstreamApi.GithubComSatstreamSsUtilsRpcUtxoRune = factory(root.SatstreamApi.ApiClient, root.SatstreamApi.BigInt);
  }
}(this, function(ApiClient, BigInt) {
  'use strict';

  /**
   * The GithubComSatstreamSsUtilsRpcUtxoRune model module.
   * @module model/GithubComSatstreamSsUtilsRpcUtxoRune
   * @version 1.0
   */

  /**
   * Constructs a new <code>GithubComSatstreamSsUtilsRpcUtxoRune</code>.
   * @alias module:model/GithubComSatstreamSsUtilsRpcUtxoRune
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>GithubComSatstreamSsUtilsRpcUtxoRune</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GithubComSatstreamSsUtilsRpcUtxoRune} obj Optional instance to populate.
   * @return {module:model/GithubComSatstreamSsUtilsRpcUtxoRune} The populated <code>GithubComSatstreamSsUtilsRpcUtxoRune</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('amount'))
        obj.amount = BigInt.constructFromObject(data['amount']);
      if (data.hasOwnProperty('rune_id'))
        obj.runeId = ApiClient.convertToType(data['rune_id'], 'String');
    }
    return obj;
  }

  /**
   * @member {module:model/BigInt} amount
   */
  exports.prototype.amount = undefined;

  /**
   * @member {String} runeId
   */
  exports.prototype.runeId = undefined;


  return exports;

}));
