/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import GithubComSatstreamSsUtilsOrdServerResponsesTransactionDetails from './GithubComSatstreamSsUtilsOrdServerResponsesTransactionDetails';

/**
 * The GithubComSatstreamSsUtilsOrdServerResponsesTransactionResponse model module.
 * @module model/GithubComSatstreamSsUtilsOrdServerResponsesTransactionResponse
 * @version 1.0.19
 */
export default class GithubComSatstreamSsUtilsOrdServerResponsesTransactionResponse {
  /**
   * Constructs a new <code>GithubComSatstreamSsUtilsOrdServerResponsesTransactionResponse</code>.
   * @alias module:model/GithubComSatstreamSsUtilsOrdServerResponsesTransactionResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GithubComSatstreamSsUtilsOrdServerResponsesTransactionResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GithubComSatstreamSsUtilsOrdServerResponsesTransactionResponse} obj Optional instance to populate.
   * @return {module:model/GithubComSatstreamSsUtilsOrdServerResponsesTransactionResponse} The populated <code>GithubComSatstreamSsUtilsOrdServerResponsesTransactionResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GithubComSatstreamSsUtilsOrdServerResponsesTransactionResponse();
      if (data.hasOwnProperty('chain'))
        obj.chain = ApiClient.convertToType(data['chain'], 'String');
      if (data.hasOwnProperty('etching'))
        obj.etching = ApiClient.convertToType(data['etching'], 'String');
      if (data.hasOwnProperty('inscription_count'))
        obj.inscriptionCount = ApiClient.convertToType(data['inscription_count'], 'Number');
      if (data.hasOwnProperty('transaction'))
        obj.transaction = GithubComSatstreamSsUtilsOrdServerResponsesTransactionDetails.constructFromObject(data['transaction']);
      if (data.hasOwnProperty('txid'))
        obj.txid = ApiClient.convertToType(data['txid'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} chain
 */
GithubComSatstreamSsUtilsOrdServerResponsesTransactionResponse.prototype.chain = undefined;

/**
 * @member {String} etching
 */
GithubComSatstreamSsUtilsOrdServerResponsesTransactionResponse.prototype.etching = undefined;

/**
 * @member {Number} inscriptionCount
 */
GithubComSatstreamSsUtilsOrdServerResponsesTransactionResponse.prototype.inscriptionCount = undefined;

/**
 * @member {module:model/GithubComSatstreamSsUtilsOrdServerResponsesTransactionDetails} transaction
 */
GithubComSatstreamSsUtilsOrdServerResponsesTransactionResponse.prototype.transaction = undefined;

/**
 * @member {String} txid
 */
GithubComSatstreamSsUtilsOrdServerResponsesTransactionResponse.prototype.txid = undefined;

