/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import GithubComSatstreamSsUtilsOrdServerResponsesTransaction from './GithubComSatstreamSsUtilsOrdServerResponsesTransaction';

/**
 * The GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse model module.
 * @module model/GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse
 * @version 1.0.19
 */
export default class GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse {
  /**
   * Constructs a new <code>GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse</code>.
   * @alias module:model/GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse} obj Optional instance to populate.
   * @return {module:model/GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse} The populated <code>GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse();
      if (data.hasOwnProperty('best_height'))
        obj.bestHeight = ApiClient.convertToType(data['best_height'], 'Number');
      if (data.hasOwnProperty('hash'))
        obj.hash = ApiClient.convertToType(data['hash'], 'String');
      if (data.hasOwnProperty('height'))
        obj.height = ApiClient.convertToType(data['height'], 'Number');
      if (data.hasOwnProperty('inscriptions'))
        obj.inscriptions = ApiClient.convertToType(data['inscriptions'], ['String']);
      if (data.hasOwnProperty('runes'))
        obj.runes = ApiClient.convertToType(data['runes'], ['String']);
      if (data.hasOwnProperty('target'))
        obj.target = ApiClient.convertToType(data['target'], 'String');
      if (data.hasOwnProperty('transactions'))
        obj.transactions = ApiClient.convertToType(data['transactions'], [GithubComSatstreamSsUtilsOrdServerResponsesTransaction]);
    }
    return obj;
  }
}

/**
 * @member {Number} bestHeight
 */
GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse.prototype.bestHeight = undefined;

/**
 * @member {String} hash
 */
GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse.prototype.hash = undefined;

/**
 * @member {Number} height
 */
GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse.prototype.height = undefined;

/**
 * @member {Array.<String>} inscriptions
 */
GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse.prototype.inscriptions = undefined;

/**
 * @member {Array.<String>} runes
 */
GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse.prototype.runes = undefined;

/**
 * @member {String} target
 */
GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse.prototype.target = undefined;

/**
 * @member {Array.<module:model/GithubComSatstreamSsUtilsOrdServerResponsesTransaction>} transactions
 */
GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse.prototype.transactions = undefined;

