/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse model module.
 * @module model/GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse
 * @version 1.0.19
 */
export default class GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse {
  /**
   * Constructs a new <code>GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse</code>.
   * @alias module:model/GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse} obj Optional instance to populate.
   * @return {module:model/GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse} The populated <code>GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse();
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], 'String');
      if (data.hasOwnProperty('indexed'))
        obj.indexed = ApiClient.convertToType(data['indexed'], 'Boolean');
      if (data.hasOwnProperty('inscriptions'))
        obj.inscriptions = ApiClient.convertToType(data['inscriptions'], ['String']);
      if (data.hasOwnProperty('outpoint'))
        obj.outpoint = ApiClient.convertToType(data['outpoint'], 'String');
      if (data.hasOwnProperty('runes'))
        obj.runes = ApiClient.convertToType(data['runes'], {'String': 'String'});
      if (data.hasOwnProperty('sat_ranges'))
        obj.satRanges = ApiClient.convertToType(data['sat_ranges'], [['Number']]);
      if (data.hasOwnProperty('script_pubkey'))
        obj.scriptPubkey = ApiClient.convertToType(data['script_pubkey'], 'String');
      if (data.hasOwnProperty('spent'))
        obj.spent = ApiClient.convertToType(data['spent'], 'Boolean');
      if (data.hasOwnProperty('transaction'))
        obj.transaction = ApiClient.convertToType(data['transaction'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} address
 */
GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse.prototype.address = undefined;

/**
 * @member {Boolean} indexed
 */
GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse.prototype.indexed = undefined;

/**
 * @member {Array.<String>} inscriptions
 */
GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse.prototype.inscriptions = undefined;

/**
 * @member {String} outpoint
 */
GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse.prototype.outpoint = undefined;

/**
 * @member {Object.<String, String>} runes
 */
GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse.prototype.runes = undefined;

/**
 * @member {Array.<Array.<Number>>} satRanges
 */
GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse.prototype.satRanges = undefined;

/**
 * @member {String} scriptPubkey
 */
GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse.prototype.scriptPubkey = undefined;

/**
 * @member {Boolean} spent
 */
GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse.prototype.spent = undefined;

/**
 * @member {String} transaction
 */
GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse.prototype.transaction = undefined;

/**
 * @member {Number} value
 */
GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse.prototype.value = undefined;

