/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GithubComSatstreamSsUtilsRpcScriptPubKey', 'model/GithubComSatstreamSsUtilsRpcUtxoRune'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GithubComSatstreamSsUtilsRpcScriptPubKey'), require('./GithubComSatstreamSsUtilsRpcUtxoRune'));
  } else {
    // Browser globals (root is window)
    if (!root.SatstreamApi) {
      root.SatstreamApi = {};
    }
    root.SatstreamApi.GithubComSatstreamSsUtilsRpcPrevOut = factory(root.SatstreamApi.ApiClient, root.SatstreamApi.GithubComSatstreamSsUtilsRpcScriptPubKey, root.SatstreamApi.GithubComSatstreamSsUtilsRpcUtxoRune);
  }
}(this, function(ApiClient, GithubComSatstreamSsUtilsRpcScriptPubKey, GithubComSatstreamSsUtilsRpcUtxoRune) {
  'use strict';

  /**
   * The GithubComSatstreamSsUtilsRpcPrevOut model module.
   * @module model/GithubComSatstreamSsUtilsRpcPrevOut
   * @version 1.0
   */

  /**
   * Constructs a new <code>GithubComSatstreamSsUtilsRpcPrevOut</code>.
   * @alias module:model/GithubComSatstreamSsUtilsRpcPrevOut
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>GithubComSatstreamSsUtilsRpcPrevOut</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GithubComSatstreamSsUtilsRpcPrevOut} obj Optional instance to populate.
   * @return {module:model/GithubComSatstreamSsUtilsRpcPrevOut} The populated <code>GithubComSatstreamSsUtilsRpcPrevOut</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('height'))
        obj.height = ApiClient.convertToType(data['height'], 'Number');
      if (data.hasOwnProperty('n'))
        obj.n = ApiClient.convertToType(data['n'], 'Number');
      if (data.hasOwnProperty('populated'))
        obj.populated = ApiClient.convertToType(data['populated'], 'Boolean');
      if (data.hasOwnProperty('rune_holdings'))
        obj.runeHoldings = ApiClient.convertToType(data['rune_holdings'], [GithubComSatstreamSsUtilsRpcUtxoRune]);
      if (data.hasOwnProperty('scriptPubKey'))
        obj.scriptPubKey = GithubComSatstreamSsUtilsRpcScriptPubKey.constructFromObject(data['scriptPubKey']);
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} height
   */
  exports.prototype.height = undefined;

  /**
   * @member {Number} n
   */
  exports.prototype.n = undefined;

  /**
   * * The populated field is used to determine if the prevout has been populated from our code or automatically by the RPC on fetch
   * @member {Boolean} populated
   */
  exports.prototype.populated = undefined;

  /**
   * @member {Array.<module:model/GithubComSatstreamSsUtilsRpcUtxoRune>} runeHoldings
   */
  exports.prototype.runeHoldings = undefined;

  /**
   * @member {module:model/GithubComSatstreamSsUtilsRpcScriptPubKey} scriptPubKey
   */
  exports.prototype.scriptPubKey = undefined;

  /**
   * @member {Number} value
   */
  exports.prototype.value = undefined;


  return exports;

}));
