/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BigInt', 'model/OrdinalsTermsRange'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BigInt'), require('./OrdinalsTermsRange'));
  } else {
    // Browser globals (root is window)
    if (!root.SatstreamApi) {
      root.SatstreamApi = {};
    }
    root.SatstreamApi.OrdinalsTerms = factory(root.SatstreamApi.ApiClient, root.SatstreamApi.BigInt, root.SatstreamApi.OrdinalsTermsRange);
  }
}(this, function(ApiClient, BigInt, OrdinalsTermsRange) {
  'use strict';

  /**
   * The OrdinalsTerms model module.
   * @module model/OrdinalsTerms
   * @version 1.0
   */

  /**
   * Constructs a new <code>OrdinalsTerms</code>.
   * @alias module:model/OrdinalsTerms
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>OrdinalsTerms</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrdinalsTerms} obj Optional instance to populate.
   * @return {module:model/OrdinalsTerms} The populated <code>OrdinalsTerms</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('amount'))
        obj.amount = BigInt.constructFromObject(data['amount']);
      if (data.hasOwnProperty('cap'))
        obj.cap = BigInt.constructFromObject(data['cap']);
      if (data.hasOwnProperty('height'))
        obj.height = OrdinalsTermsRange.constructFromObject(data['height']);
      if (data.hasOwnProperty('offset'))
        obj.offset = OrdinalsTermsRange.constructFromObject(data['offset']);
    }
    return obj;
  }

  /**
   * @member {module:model/BigInt} amount
   */
  exports.prototype.amount = undefined;

  /**
   * @member {module:model/BigInt} cap
   */
  exports.prototype.cap = undefined;

  /**
   * @member {module:model/OrdinalsTermsRange} height
   */
  exports.prototype.height = undefined;

  /**
   * @member {module:model/OrdinalsTermsRange} offset
   */
  exports.prototype.offset = undefined;


  return exports;

}));
