/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PSBTBip32Deriv model module.
 * @module model/PSBTBip32Deriv
 * @version 1.0.37
 */
export default class PSBTBip32Deriv {
  /**
   * Constructs a new <code>PSBTBip32Deriv</code>.
   * @alias module:model/PSBTBip32Deriv
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PSBTBip32Deriv</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PSBTBip32Deriv} obj Optional instance to populate.
   * @return {module:model/PSBTBip32Deriv} The populated <code>PSBTBip32Deriv</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PSBTBip32Deriv();
      if (data.hasOwnProperty('master_fingerprint'))
        obj.masterFingerprint = ApiClient.convertToType(data['master_fingerprint'], 'String');
      if (data.hasOwnProperty('path'))
        obj.path = ApiClient.convertToType(data['path'], 'String');
      if (data.hasOwnProperty('pubkey'))
        obj.pubkey = ApiClient.convertToType(data['pubkey'], 'String');
    }
    return obj;
  }
}

/**
 * The fingerprint of the master key
 * @member {String} masterFingerprint
 */
PSBTBip32Deriv.prototype.masterFingerprint = undefined;

/**
 * The derivation path
 * @member {String} path
 */
PSBTBip32Deriv.prototype.path = undefined;

/**
 * The public key
 * @member {String} pubkey
 */
PSBTBip32Deriv.prototype.pubkey = undefined;

