/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The RequestsCreatePSBTOutput model module.
 * @module model/RequestsCreatePSBTOutput
 * @version 1.0.20
 */
export default class RequestsCreatePSBTOutput {
  /**
   * Constructs a new <code>RequestsCreatePSBTOutput</code>.
   * @alias module:model/RequestsCreatePSBTOutput
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RequestsCreatePSBTOutput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RequestsCreatePSBTOutput} obj Optional instance to populate.
   * @return {module:model/RequestsCreatePSBTOutput} The populated <code>RequestsCreatePSBTOutput</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RequestsCreatePSBTOutput();
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], 'String');
    }
    return obj;
  }
}

/**
 * The bitcoin address to send to
 * @member {String} address
 */
RequestsCreatePSBTOutput.prototype.address = undefined;

/**
 * Hex-encoded data to embed in the transaction
 * @member {String} data
 */
RequestsCreatePSBTOutput.prototype.data = undefined;

