/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import RequestsCreatePSBTInput from './RequestsCreatePSBTInput';
import RequestsCreatePSBTOutput from './RequestsCreatePSBTOutput';

/**
 * The RequestsCreatePSBTRequest model module.
 * @module model/RequestsCreatePSBTRequest
 * @version 1.0.22
 */
export default class RequestsCreatePSBTRequest {
  /**
   * Constructs a new <code>RequestsCreatePSBTRequest</code>.
   * @alias module:model/RequestsCreatePSBTRequest
   * @class
   * @param inputs {Array.<module:model/RequestsCreatePSBTInput>} The inputs for the transaction
   * @param outputs {Array.<module:model/RequestsCreatePSBTOutput>} The outputs for the transaction (each address can only appear once)
   */
  constructor(inputs, outputs) {
    this.inputs = inputs;
    this.outputs = outputs;
  }

  /**
   * Constructs a <code>RequestsCreatePSBTRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RequestsCreatePSBTRequest} obj Optional instance to populate.
   * @return {module:model/RequestsCreatePSBTRequest} The populated <code>RequestsCreatePSBTRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RequestsCreatePSBTRequest();
      if (data.hasOwnProperty('inputs'))
        obj.inputs = ApiClient.convertToType(data['inputs'], [RequestsCreatePSBTInput]);
      if (data.hasOwnProperty('locktime'))
        obj.locktime = ApiClient.convertToType(data['locktime'], 'Number');
      if (data.hasOwnProperty('outputs'))
        obj.outputs = ApiClient.convertToType(data['outputs'], [RequestsCreatePSBTOutput]);
      if (data.hasOwnProperty('replaceable'))
        obj.replaceable = ApiClient.convertToType(data['replaceable'], 'Boolean');
    }
    return obj;
  }
}

/**
 * The inputs for the transaction
 * @member {Array.<module:model/RequestsCreatePSBTInput>} inputs
 */
RequestsCreatePSBTRequest.prototype.inputs = undefined;

/**
 * Raw locktime. Non-0 value also locktime-activates inputs
 * @member {Number} locktime
 */
RequestsCreatePSBTRequest.prototype.locktime = undefined;

/**
 * The outputs for the transaction (each address can only appear once)
 * @member {Array.<module:model/RequestsCreatePSBTOutput>} outputs
 */
RequestsCreatePSBTRequest.prototype.outputs = undefined;

/**
 * Marks this transaction as BIP125-replaceable
 * @member {Boolean} replaceable
 */
RequestsCreatePSBTRequest.prototype.replaceable = undefined;

