/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ResponsesSendRawTransactionData from './ResponsesSendRawTransactionData';

/**
 * The ResponsesSendRawTransaction model module.
 * @module model/ResponsesSendRawTransaction
 * @version 1.0.0
 */
export default class ResponsesSendRawTransaction {
  /**
   * Constructs a new <code>ResponsesSendRawTransaction</code>.
   * @alias module:model/ResponsesSendRawTransaction
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResponsesSendRawTransaction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponsesSendRawTransaction} obj Optional instance to populate.
   * @return {module:model/ResponsesSendRawTransaction} The populated <code>ResponsesSendRawTransaction</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResponsesSendRawTransaction();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'Number');
      if (data.hasOwnProperty('data'))
        obj.data = ResponsesSendRawTransactionData.constructFromObject(data['data']);
      if (data.hasOwnProperty('msg'))
        obj.msg = ApiClient.convertToType(data['msg'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} code
 */
ResponsesSendRawTransaction.prototype.code = undefined;

/**
 * @member {module:model/ResponsesSendRawTransactionData} data
 */
ResponsesSendRawTransaction.prototype.data = undefined;

/**
 * @member {String} msg
 */
ResponsesSendRawTransaction.prototype.msg = undefined;

