/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import BigInt from './BigInt';

/**
 * The ResponsesNonInscriptionUTXO model module.
 * @module model/ResponsesNonInscriptionUTXO
 * @version 1.0.8
 */
export default class ResponsesNonInscriptionUTXO {
  /**
   * Constructs a new <code>ResponsesNonInscriptionUTXO</code>.
   * @alias module:model/ResponsesNonInscriptionUTXO
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResponsesNonInscriptionUTXO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponsesNonInscriptionUTXO} obj Optional instance to populate.
   * @return {module:model/ResponsesNonInscriptionUTXO} The populated <code>ResponsesNonInscriptionUTXO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResponsesNonInscriptionUTXO();
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], 'String');
      if (data.hasOwnProperty('codeType'))
        obj.codeType = ApiClient.convertToType(data['codeType'], 'Number');
      if (data.hasOwnProperty('height'))
        obj.height = ApiClient.convertToType(data['height'], 'Number');
      if (data.hasOwnProperty('idx'))
        obj.idx = ApiClient.convertToType(data['idx'], 'Number');
      if (data.hasOwnProperty('isOpInRBF'))
        obj.isOpInRBF = ApiClient.convertToType(data['isOpInRBF'], 'Boolean');
      if (data.hasOwnProperty('isSpent'))
        obj.isSpent = ApiClient.convertToType(data['isSpent'], 'Boolean');
      if (data.hasOwnProperty('satoshi'))
        obj.satoshi = BigInt.constructFromObject(data['satoshi']);
      if (data.hasOwnProperty('scriptPk'))
        obj.scriptPk = ApiClient.convertToType(data['scriptPk'], 'String');
      if (data.hasOwnProperty('scriptType'))
        obj.scriptType = ApiClient.convertToType(data['scriptType'], 'String');
      if (data.hasOwnProperty('txid'))
        obj.txid = ApiClient.convertToType(data['txid'], 'String');
      if (data.hasOwnProperty('vout'))
        obj.vout = ApiClient.convertToType(data['vout'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} address
 */
ResponsesNonInscriptionUTXO.prototype.address = undefined;

/**
 * @member {Number} codeType
 */
ResponsesNonInscriptionUTXO.prototype.codeType = undefined;

/**
 * @member {Number} height
 */
ResponsesNonInscriptionUTXO.prototype.height = undefined;

/**
 * @member {Number} idx
 */
ResponsesNonInscriptionUTXO.prototype.idx = undefined;

/**
 * @member {Boolean} isOpInRBF
 */
ResponsesNonInscriptionUTXO.prototype.isOpInRBF = undefined;

/**
 * @member {Boolean} isSpent
 */
ResponsesNonInscriptionUTXO.prototype.isSpent = undefined;

/**
 * @member {module:model/BigInt} satoshi
 */
ResponsesNonInscriptionUTXO.prototype.satoshi = undefined;

/**
 * @member {String} scriptPk
 */
ResponsesNonInscriptionUTXO.prototype.scriptPk = undefined;

/**
 * @member {String} scriptType
 */
ResponsesNonInscriptionUTXO.prototype.scriptType = undefined;

/**
 * @member {String} txid
 */
ResponsesNonInscriptionUTXO.prototype.txid = undefined;

/**
 * @member {Number} vout
 */
ResponsesNonInscriptionUTXO.prototype.vout = undefined;

