/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SatstreamApi) {
      root.SatstreamApi = {};
    }
    root.SatstreamApi.ResponsesGetAddressRuneBalanceData = factory(root.SatstreamApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ResponsesGetAddressRuneBalanceData model module.
   * @module model/ResponsesGetAddressRuneBalanceData
   * @version 1.0
   */

  /**
   * Constructs a new <code>ResponsesGetAddressRuneBalanceData</code>.
   * @alias module:model/ResponsesGetAddressRuneBalanceData
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ResponsesGetAddressRuneBalanceData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponsesGetAddressRuneBalanceData} obj Optional instance to populate.
   * @return {module:model/ResponsesGetAddressRuneBalanceData} The populated <code>ResponsesGetAddressRuneBalanceData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'String');
      if (data.hasOwnProperty('divisibility'))
        obj.divisibility = ApiClient.convertToType(data['divisibility'], 'Number');
      if (data.hasOwnProperty('rune'))
        obj.rune = ApiClient.convertToType(data['rune'], 'String');
      if (data.hasOwnProperty('runeid'))
        obj.runeid = ApiClient.convertToType(data['runeid'], 'String');
      if (data.hasOwnProperty('spacedAmount'))
        obj.spacedAmount = ApiClient.convertToType(data['spacedAmount'], 'String');
      if (data.hasOwnProperty('spacedRune'))
        obj.spacedRune = ApiClient.convertToType(data['spacedRune'], 'String');
      if (data.hasOwnProperty('symbol'))
        obj.symbol = ApiClient.convertToType(data['symbol'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} amount
   */
  exports.prototype.amount = undefined;

  /**
   * @member {Number} divisibility
   */
  exports.prototype.divisibility = undefined;

  /**
   * @member {String} rune
   */
  exports.prototype.rune = undefined;

  /**
   * @member {String} runeid
   */
  exports.prototype.runeid = undefined;

  /**
   * @member {String} spacedAmount
   */
  exports.prototype.spacedAmount = undefined;

  /**
   * @member {String} spacedRune
   */
  exports.prototype.spacedRune = undefined;

  /**
   * @member {String} symbol
   */
  exports.prototype.symbol = undefined;


  return exports;

}));
