/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import GithubComSatstreamSsUtilsRpcBtcTx from './GithubComSatstreamSsUtilsRpcBtcTx';

/**
 * The ResponsesGetMempoolTransactions model module.
 * @module model/ResponsesGetMempoolTransactions
 * @version 1.0.16
 */
export default class ResponsesGetMempoolTransactions {
  /**
   * Constructs a new <code>ResponsesGetMempoolTransactions</code>.
   * @alias module:model/ResponsesGetMempoolTransactions
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResponsesGetMempoolTransactions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponsesGetMempoolTransactions} obj Optional instance to populate.
   * @return {module:model/ResponsesGetMempoolTransactions} The populated <code>ResponsesGetMempoolTransactions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResponsesGetMempoolTransactions();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'Number');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [GithubComSatstreamSsUtilsRpcBtcTx]);
      if (data.hasOwnProperty('msg'))
        obj.msg = ApiClient.convertToType(data['msg'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} code
 */
ResponsesGetMempoolTransactions.prototype.code = undefined;

/**
 * @member {Array.<module:model/GithubComSatstreamSsUtilsRpcBtcTx>} data
 */
ResponsesGetMempoolTransactions.prototype.data = undefined;

/**
 * @member {String} msg
 */
ResponsesGetMempoolTransactions.prototype.msg = undefined;

