/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SatstreamApi) {
      root.SatstreamApi = {};
    }
    root.SatstreamApi.ResponsesBlockRange = factory(root.SatstreamApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ResponsesBlockRange model module.
   * @module model/ResponsesBlockRange
   * @version 1.0
   */

  /**
   * Constructs a new <code>ResponsesBlockRange</code>.
   * @alias module:model/ResponsesBlockRange
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ResponsesBlockRange</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponsesBlockRange} obj Optional instance to populate.
   * @return {module:model/ResponsesBlockRange} The populated <code>ResponsesBlockRange</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('end'))
        obj.end = ApiClient.convertToType(data['end'], 'Number');
      if (data.hasOwnProperty('start'))
        obj.start = ApiClient.convertToType(data['start'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} end
   */
  exports.prototype.end = undefined;

  /**
   * @member {Number} start
   */
  exports.prototype.start = undefined;


  return exports;

}));
