/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BigInt'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BigInt'));
  } else {
    // Browser globals (root is window)
    if (!root.SatstreamApi) {
      root.SatstreamApi = {};
    }
    root.SatstreamApi.ResponsesNonInscriptionUTXO = factory(root.SatstreamApi.ApiClient, root.SatstreamApi.BigInt);
  }
}(this, function(ApiClient, BigInt) {
  'use strict';

  /**
   * The ResponsesNonInscriptionUTXO model module.
   * @module model/ResponsesNonInscriptionUTXO
   * @version 1.0
   */

  /**
   * Constructs a new <code>ResponsesNonInscriptionUTXO</code>.
   * @alias module:model/ResponsesNonInscriptionUTXO
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ResponsesNonInscriptionUTXO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponsesNonInscriptionUTXO} obj Optional instance to populate.
   * @return {module:model/ResponsesNonInscriptionUTXO} The populated <code>ResponsesNonInscriptionUTXO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], 'String');
      if (data.hasOwnProperty('codeType'))
        obj.codeType = ApiClient.convertToType(data['codeType'], 'Number');
      if (data.hasOwnProperty('height'))
        obj.height = ApiClient.convertToType(data['height'], 'Number');
      if (data.hasOwnProperty('idx'))
        obj.idx = ApiClient.convertToType(data['idx'], 'Number');
      if (data.hasOwnProperty('isOpInRBF'))
        obj.isOpInRBF = ApiClient.convertToType(data['isOpInRBF'], 'Boolean');
      if (data.hasOwnProperty('isSpent'))
        obj.isSpent = ApiClient.convertToType(data['isSpent'], 'Boolean');
      if (data.hasOwnProperty('satoshi'))
        obj.satoshi = BigInt.constructFromObject(data['satoshi']);
      if (data.hasOwnProperty('scriptPk'))
        obj.scriptPk = ApiClient.convertToType(data['scriptPk'], 'String');
      if (data.hasOwnProperty('scriptType'))
        obj.scriptType = ApiClient.convertToType(data['scriptType'], 'String');
      if (data.hasOwnProperty('txid'))
        obj.txid = ApiClient.convertToType(data['txid'], 'String');
      if (data.hasOwnProperty('vout'))
        obj.vout = ApiClient.convertToType(data['vout'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} address
   */
  exports.prototype.address = undefined;

  /**
   * @member {Number} codeType
   */
  exports.prototype.codeType = undefined;

  /**
   * @member {Number} height
   */
  exports.prototype.height = undefined;

  /**
   * @member {Number} idx
   */
  exports.prototype.idx = undefined;

  /**
   * @member {Boolean} isOpInRBF
   */
  exports.prototype.isOpInRBF = undefined;

  /**
   * @member {Boolean} isSpent
   */
  exports.prototype.isSpent = undefined;

  /**
   * @member {module:model/BigInt} satoshi
   */
  exports.prototype.satoshi = undefined;

  /**
   * @member {String} scriptPk
   */
  exports.prototype.scriptPk = undefined;

  /**
   * @member {String} scriptType
   */
  exports.prototype.scriptType = undefined;

  /**
   * @member {String} txid
   */
  exports.prototype.txid = undefined;

  /**
   * @member {Number} vout
   */
  exports.prototype.vout = undefined;


  return exports;

}));
