/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ResponsesGetAddressRuneBalanceData model module.
 * @module model/ResponsesGetAddressRuneBalanceData
 * @version 1.0.8
 */
export default class ResponsesGetAddressRuneBalanceData {
  /**
   * Constructs a new <code>ResponsesGetAddressRuneBalanceData</code>.
   * @alias module:model/ResponsesGetAddressRuneBalanceData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResponsesGetAddressRuneBalanceData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponsesGetAddressRuneBalanceData} obj Optional instance to populate.
   * @return {module:model/ResponsesGetAddressRuneBalanceData} The populated <code>ResponsesGetAddressRuneBalanceData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResponsesGetAddressRuneBalanceData();
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'String');
      if (data.hasOwnProperty('divisibility'))
        obj.divisibility = ApiClient.convertToType(data['divisibility'], 'Number');
      if (data.hasOwnProperty('rune'))
        obj.rune = ApiClient.convertToType(data['rune'], 'String');
      if (data.hasOwnProperty('runeid'))
        obj.runeid = ApiClient.convertToType(data['runeid'], 'String');
      if (data.hasOwnProperty('spacedAmount'))
        obj.spacedAmount = ApiClient.convertToType(data['spacedAmount'], 'String');
      if (data.hasOwnProperty('spacedRune'))
        obj.spacedRune = ApiClient.convertToType(data['spacedRune'], 'String');
      if (data.hasOwnProperty('symbol'))
        obj.symbol = ApiClient.convertToType(data['symbol'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} amount
 */
ResponsesGetAddressRuneBalanceData.prototype.amount = undefined;

/**
 * @member {Number} divisibility
 */
ResponsesGetAddressRuneBalanceData.prototype.divisibility = undefined;

/**
 * @member {String} rune
 */
ResponsesGetAddressRuneBalanceData.prototype.rune = undefined;

/**
 * @member {String} runeid
 */
ResponsesGetAddressRuneBalanceData.prototype.runeid = undefined;

/**
 * @member {String} spacedAmount
 */
ResponsesGetAddressRuneBalanceData.prototype.spacedAmount = undefined;

/**
 * @member {String} spacedRune
 */
ResponsesGetAddressRuneBalanceData.prototype.spacedRune = undefined;

/**
 * @member {String} symbol
 */
ResponsesGetAddressRuneBalanceData.prototype.symbol = undefined;

