/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ResponsesGetRawMempoolResponse model module.
 * @module model/ResponsesGetRawMempoolResponse
 * @version 1.0.19
 */
export default class ResponsesGetRawMempoolResponse {
  /**
   * Constructs a new <code>ResponsesGetRawMempoolResponse</code>.
   * @alias module:model/ResponsesGetRawMempoolResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResponsesGetRawMempoolResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponsesGetRawMempoolResponse} obj Optional instance to populate.
   * @return {module:model/ResponsesGetRawMempoolResponse} The populated <code>ResponsesGetRawMempoolResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResponsesGetRawMempoolResponse();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'Number');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], Object);
      if (data.hasOwnProperty('msg'))
        obj.msg = ApiClient.convertToType(data['msg'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} code
 */
ResponsesGetRawMempoolResponse.prototype.code = undefined;

/**
 * Either []string, map[string]MempoolEntry, or *MempoolSequence
 * @member {Object} data
 */
ResponsesGetRawMempoolResponse.prototype.data = undefined;

/**
 * @member {String} msg
 */
ResponsesGetRawMempoolResponse.prototype.msg = undefined;

