/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SatstreamApi) {
      root.SatstreamApi = {};
    }
    root.SatstreamApi.RpcScriptPubKey = factory(root.SatstreamApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The RpcScriptPubKey model module.
   * @module model/RpcScriptPubKey
   * @version 1.0
   */

  /**
   * Constructs a new <code>RpcScriptPubKey</code>.
   * @alias module:model/RpcScriptPubKey
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RpcScriptPubKey</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RpcScriptPubKey} obj Optional instance to populate.
   * @return {module:model/RpcScriptPubKey} The populated <code>RpcScriptPubKey</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], 'String');
      if (data.hasOwnProperty('asm'))
        obj.asm = ApiClient.convertToType(data['asm'], 'String');
      if (data.hasOwnProperty('desc'))
        obj.desc = ApiClient.convertToType(data['desc'], 'String');
      if (data.hasOwnProperty('hex'))
        obj.hex = ApiClient.convertToType(data['hex'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} address
   */
  exports.prototype.address = undefined;

  /**
   * @member {String} asm
   */
  exports.prototype.asm = undefined;

  /**
   * @member {String} desc
   */
  exports.prototype.desc = undefined;

  /**
   * @member {String} hex
   */
  exports.prototype.hex = undefined;

  /**
   * @member {String} type
   */
  exports.prototype.type = undefined;


  return exports;

}));
