/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The RunestoneData model module.
 * @module model/RunestoneData
 * @version 1.0.48
 */
export default class RunestoneData {
  /**
   * Constructs a new <code>RunestoneData</code>.
   * @alias module:model/RunestoneData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RunestoneData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RunestoneData} obj Optional instance to populate.
   * @return {module:model/RunestoneData} The populated <code>RunestoneData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RunestoneData();
      if (data.hasOwnProperty('edicts'))
        obj.edicts = ApiClient.convertToType(data['edicts'], [['Number']]);
      if (data.hasOwnProperty('etching'))
        obj.etching = ApiClient.convertToType(data['etching'], 'String');
      if (data.hasOwnProperty('mint'))
        obj.mint = ApiClient.convertToType(data['mint'], 'String');
      if (data.hasOwnProperty('pointer'))
        obj.pointer = ApiClient.convertToType(data['pointer'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Array.<Array.<Number>>} edicts
 */
RunestoneData.prototype.edicts = undefined;

/**
 * @member {String} etching
 */
RunestoneData.prototype.etching = undefined;

/**
 * @member {String} mint
 */
RunestoneData.prototype.mint = undefined;

/**
 * @member {Number} pointer
 */
RunestoneData.prototype.pointer = undefined;

