/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TransactionGetTxOutSetInfoRequest model module.
 * @module model/TransactionGetTxOutSetInfoRequest
 * @version 1.0.32
 */
export default class TransactionGetTxOutSetInfoRequest {
  /**
   * Constructs a new <code>TransactionGetTxOutSetInfoRequest</code>.
   * @alias module:model/TransactionGetTxOutSetInfoRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TransactionGetTxOutSetInfoRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionGetTxOutSetInfoRequest} obj Optional instance to populate.
   * @return {module:model/TransactionGetTxOutSetInfoRequest} The populated <code>TransactionGetTxOutSetInfoRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TransactionGetTxOutSetInfoRequest();
      if (data.hasOwnProperty('hash_or_height'))
        obj.hashOrHeight = ApiClient.convertToType(data['hash_or_height'], Object);
      if (data.hasOwnProperty('hash_type'))
        obj.hashType = ApiClient.convertToType(data['hash_type'], 'String');
      if (data.hasOwnProperty('use_index'))
        obj.useIndex = ApiClient.convertToType(data['use_index'], 'Boolean');
    }
    return obj;
  }
}

/**
 * Block hash or height
 * @member {Object} hashOrHeight
 */
TransactionGetTxOutSetInfoRequest.prototype.hashOrHeight = undefined;

/**
 * Which UTXO set hash should be calculated
 * @member {String} hashType
 */
TransactionGetTxOutSetInfoRequest.prototype.hashType = undefined;

/**
 * Whether to use coinstatsindex
 * @member {Boolean} useIndex
 */
TransactionGetTxOutSetInfoRequest.prototype.useIndex = undefined;

