/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import GetSatoshiResponse from '../model/GetSatoshiResponse';
import UtilsResponseEnvelope from '../model/UtilsResponseEnvelope';

/**
* Satoshis service.
* @module api/SatoshisApi
* @version 1.0.37
*/
export default class SatoshisApi {

    /**
    * Constructs a new SatoshisApi. 
    * @alias module:api/SatoshisApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getSatoshi operation.
     * @callback moduleapi/SatoshisApi~getSatoshiCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetSatoshiResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get satoshi info
     * Retrieve information about a specific satoshi
     * @param {Number} _number Satoshi Number
     * @param {module:api/SatoshisApi~getSatoshiCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getSatoshi(_number, callback) {
      
      let postBody = null;
      // verify the required parameter '_number' is set
      if (_number === undefined || _number === null) {
        throw new Error("Missing the required parameter '_number' when calling getSatoshi");
      }

      let pathParams = {
        'number': _number
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetSatoshiResponse;

      return this.apiClient.callApi(
        '/sat/{number}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}