/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SatstreamApi);
  }
}(this, function(expect, SatstreamApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2008', function() {
      beforeEach(function() {
        instance = new SatstreamApi.InlineResponse2008();
      });

      it('should create an instance of InlineResponse2008', function() {
        // TODO: update the code to test InlineResponse2008
        expect(instance).to.be.a(SatstreamApi.InlineResponse2008);
      });

      it('should have the property data (base name: "data")', function() {
        // TODO: update the code to test the property data
        expect(instance).to.have.property('data');
        // expect(instance.data).to.be(expectedValueLiteral);
      });

      it('should have the property githubComSatstreamSsApiServerApiTransactionsResponsesBaseResponse (base name: "github_com_satstream_ss-api_server_api_transactions_responses.BaseResponse")', function() {
        // TODO: update the code to test the property githubComSatstreamSsApiServerApiTransactionsResponsesBaseResponse
        expect(instance).to.have.property('githubComSatstreamSsApiServerApiTransactionsResponsesBaseResponse');
        // expect(instance.githubComSatstreamSsApiServerApiTransactionsResponsesBaseResponse).to.be(expectedValueLiteral);
      });

    });
  });

}));
