/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SatstreamJavascriptSdk);
  }
}(this, function(expect, SatstreamJavascriptSdk) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Input', function() {
      beforeEach(function() {
        instance = new SatstreamJavascriptSdk.Input();
      });

      it('should create an instance of Input', function() {
        // TODO: update the code to test Input
        expect(instance).to.be.a(SatstreamJavascriptSdk.Input);
      });

      it('should have the property previousOutput (base name: "previous_output")', function() {
        // TODO: update the code to test the property previousOutput
        expect(instance).to.have.property('previousOutput');
        // expect(instance.previousOutput).to.be(expectedValueLiteral);
      });

      it('should have the property scriptSig (base name: "script_sig")', function() {
        // TODO: update the code to test the property scriptSig
        expect(instance).to.have.property('scriptSig');
        // expect(instance.scriptSig).to.be(expectedValueLiteral);
      });

      it('should have the property sequence (base name: "sequence")', function() {
        // TODO: update the code to test the property sequence
        expect(instance).to.have.property('sequence');
        // expect(instance.sequence).to.be(expectedValueLiteral);
      });

      it('should have the property witness (base name: "witness")', function() {
        // TODO: update the code to test the property witness
        expect(instance).to.have.property('witness');
        // expect(instance.witness).to.be(expectedValueLiteral);
      });

    });
  });

}));
