/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SatstreamJavascriptSdk);
  }
}(this, function(expect, SatstreamJavascriptSdk) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PSBTBip32Deriv', function() {
      beforeEach(function() {
        instance = new SatstreamJavascriptSdk.PSBTBip32Deriv();
      });

      it('should create an instance of PSBTBip32Deriv', function() {
        // TODO: update the code to test PSBTBip32Deriv
        expect(instance).to.be.a(SatstreamJavascriptSdk.PSBTBip32Deriv);
      });

      it('should have the property masterFingerprint (base name: "master_fingerprint")', function() {
        // TODO: update the code to test the property masterFingerprint
        expect(instance).to.have.property('masterFingerprint');
        // expect(instance.masterFingerprint).to.be(expectedValueLiteral);
      });

      it('should have the property path (base name: "path")', function() {
        // TODO: update the code to test the property path
        expect(instance).to.have.property('path');
        // expect(instance.path).to.be(expectedValueLiteral);
      });

      it('should have the property pubkey (base name: "pubkey")', function() {
        // TODO: update the code to test the property pubkey
        expect(instance).to.have.property('pubkey');
        // expect(instance.pubkey).to.be(expectedValueLiteral);
      });

    });
  });

}));
