/*
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import AddressResponse from './model/AddressResponse';
import AddressRuneDelta from './model/AddressRuneDelta';
import AllOfBlockVin2ScriptSig from './model/AllOfBlockVin2ScriptSig';
import AllOfBlockVin3Prevout from './model/AllOfBlockVin3Prevout';
import AllOfDecodedPSBTInputFinalScriptsig from './model/AllOfDecodedPSBTInputFinalScriptsig';
import AllOfDecodedPSBTInputNonWitnessUtxo from './model/AllOfDecodedPSBTInputNonWitnessUtxo';
import AllOfDecodedPSBTInputRedeemScript from './model/AllOfDecodedPSBTInputRedeemScript';
import AllOfDecodedPSBTInputUnknown from './model/AllOfDecodedPSBTInputUnknown';
import AllOfDecodedPSBTInputWitnessScript from './model/AllOfDecodedPSBTInputWitnessScript';
import AllOfDecodedPSBTInputWitnessUtxo from './model/AllOfDecodedPSBTInputWitnessUtxo';
import AllOfDecodedPSBTOutputRedeemScript from './model/AllOfDecodedPSBTOutputRedeemScript';
import AllOfDecodedPSBTOutputUnknown from './model/AllOfDecodedPSBTOutputUnknown';
import AllOfDecodedPSBTOutputWitnessScript from './model/AllOfDecodedPSBTOutputWitnessScript';
import AllOfDecodedPSBTTx from './model/AllOfDecodedPSBTTx';
import AllOfDecodedPSBTUnknown from './model/AllOfDecodedPSBTUnknown';
import AllOfDecodedScriptSegwit from './model/AllOfDecodedScriptSegwit';
import AllOfFeeHorizonEstimateFail from './model/AllOfFeeHorizonEstimateFail';
import AllOfFeeHorizonEstimatePass from './model/AllOfFeeHorizonEstimatePass';
import AllOfMempoolEntryFees from './model/AllOfMempoolEntryFees';
import AllOfPSBTWitnessUtxoScriptPubKey from './model/AllOfPSBTWitnessUtxoScriptPubKey';
import AllOfRawFeeEstimateMedium from './model/AllOfRawFeeEstimateMedium';
import AllOfRawFeeEstimateModelLong from './model/AllOfRawFeeEstimateModelLong';
import AllOfRawFeeEstimateModelShort from './model/AllOfRawFeeEstimateModelShort';
import AllOfRawMempoolDataSequence from './model/AllOfRawMempoolDataSequence';
import AllOfTestMempoolAcceptResultFees from './model/AllOfTestMempoolAcceptResultFees';
import AllOfTxOutScriptPubKey from './model/AllOfTxOutScriptPubKey';
import AllOfUTXOBlockInfoUnspendables from './model/AllOfUTXOBlockInfoUnspendables';
import AllOfUTXOSetInfoBlockInfo from './model/AllOfUTXOSetInfoBlockInfo';
import AnalyzePSBTRequest from './model/AnalyzePSBTRequest';
import AnalyzePSBTResponse from './model/AnalyzePSBTResponse';
import BigInt from './model/BigInt';
import Bip32Deriv from './model/Bip32Deriv';
import Block1 from './model/Block1';
import Block2 from './model/Block2';
import Block3 from './model/Block3';
import BlockResponse from './model/BlockResponse';
import BlockStats from './model/BlockStats';
import BlockVin2 from './model/BlockVin2';
import BlockVin3 from './model/BlockVin3';
import BlockchainInfo from './model/BlockchainInfo';
import BlocksResponse from './model/BlocksResponse';
import BtcTx2 from './model/BtcTx2';
import BtcTx3 from './model/BtcTx3';
import ChainTxStats from './model/ChainTxStats';
import CombinePSBTRequest from './model/CombinePSBTRequest';
import CombinePSBTResponse from './model/CombinePSBTResponse';
import CombineRawTransactionResponse from './model/CombineRawTransactionResponse';
import ConvertToPSBTResponse from './model/ConvertToPSBTResponse';
import CreatePSBTInput from './model/CreatePSBTInput';
import CreatePSBTRequest from './model/CreatePSBTRequest';
import CreatePSBTResponse from './model/CreatePSBTResponse';
import CreateRawTransactionResponse from './model/CreateRawTransactionResponse';
import DecodePSBTRequest from './model/DecodePSBTRequest';
import DecodePSBTResponse from './model/DecodePSBTResponse';
import DecodeResponse from './model/DecodeResponse';
import DecodeScriptRequest from './model/DecodeScriptRequest';
import DecodeScriptResponse from './model/DecodeScriptResponse';
import DecodeTransactionResponse from './model/DecodeTransactionResponse';
import DecodedInscription from './model/DecodedInscription';
import DecodedPSBT from './model/DecodedPSBT';
import DecodedPSBTInput from './model/DecodedPSBTInput';
import DecodedPSBTOutput from './model/DecodedPSBTOutput';
import DecodedScript from './model/DecodedScript';
import EstimateRawFeeRequest from './model/EstimateRawFeeRequest';
import EstimateRawFeeResponse from './model/EstimateRawFeeResponse';
import EstimateSmartFeeRequest from './model/EstimateSmartFeeRequest';
import EstimateSmartFeeResponse from './model/EstimateSmartFeeResponse';
import FeeHorizonEstimate from './model/FeeHorizonEstimate';
import FeeRange from './model/FeeRange';
import FetchInscriptionsResponse from './model/FetchInscriptionsResponse';
import GetAddressDeltasResponse from './model/GetAddressDeltasResponse';
import GetAddressResponse from './model/GetAddressResponse';
import GetAddressRuneDeltasResponse from './model/GetAddressRuneDeltasResponse';
import GetAddressUTXOsResponse from './model/GetAddressUTXOsResponse';
import GetBlockCountResponse from './model/GetBlockCountResponse';
import GetBlockDecodedResponse from './model/GetBlockDecodedResponse';
import GetBlockHashByHeightResponse from './model/GetBlockHashByHeightResponse';
import GetBlockHexResponse from './model/GetBlockHexResponse';
import GetBlockInscriptionsResponse from './model/GetBlockInscriptionsResponse';
import GetBlockPrevoutResponse from './model/GetBlockPrevoutResponse';
import GetBlockResponse from './model/GetBlockResponse';
import GetBlockStatsRequest from './model/GetBlockStatsRequest';
import GetBlockStatsResponse from './model/GetBlockStatsResponse';
import GetBlockSummaryResponse from './model/GetBlockSummaryResponse';
import GetBlockchainInfoResponse from './model/GetBlockchainInfoResponse';
import GetBlocksResponse from './model/GetBlocksResponse';
import GetChainTxStatsRequest from './model/GetChainTxStatsRequest';
import GetChainTxStatsResponse from './model/GetChainTxStatsResponse';
import GetDifficultyResponse from './model/GetDifficultyResponse';
import GetInscriptionChildResponse from './model/GetInscriptionChildResponse';
import GetInscriptionResponse from './model/GetInscriptionResponse';
import GetLatestBlockHashResponse from './model/GetLatestBlockHashResponse';
import GetLatestBlockHeightResponse from './model/GetLatestBlockHeightResponse';
import GetLatestBlockTimeResponse from './model/GetLatestBlockTimeResponse';
import GetLatestInscriptionsResponse from './model/GetLatestInscriptionsResponse';
import GetLatestRunesResponse from './model/GetLatestRunesResponse';
import GetMempoolAncestorsRequest from './model/GetMempoolAncestorsRequest';
import GetMempoolAncestorsResponse from './model/GetMempoolAncestorsResponse';
import GetMempoolDescendantsRequest from './model/GetMempoolDescendantsRequest';
import GetMempoolDescendantsResponse from './model/GetMempoolDescendantsResponse';
import GetMempoolInfoResponse from './model/GetMempoolInfoResponse';
import GetMiningInfoResponse from './model/GetMiningInfoResponse';
import GetNetworkHashPSRequest from './model/GetNetworkHashPSRequest';
import GetNetworkHashPSResponse from './model/GetNetworkHashPSResponse';
import GetRawMempoolRequest from './model/GetRawMempoolRequest';
import GetRawMempoolResponse from './model/GetRawMempoolResponse';
import GetRawTransactionDecodeResponse from './model/GetRawTransactionDecodeResponse';
import GetRawTransactionHexResponse from './model/GetRawTransactionHexResponse';
import GetRawTransactionPrevoutResponse from './model/GetRawTransactionPrevoutResponse';
import GetRuneResponse from './model/GetRuneResponse';
import GetSatoshiResponse from './model/GetSatoshiResponse';
import GetStatusResponse from './model/GetStatusResponse';
import GetTxOutProofResponse from './model/GetTxOutProofResponse';
import GetTxOutResponse from './model/GetTxOutResponse';
import GetTxSpendingPrevoutResponse from './model/GetTxSpendingPrevoutResponse';
import GithubComSatstreamSsUtilsDatabaseAddressDelta from './model/GithubComSatstreamSsUtilsDatabaseAddressDelta';
import GithubComSatstreamSsUtilsOrdServerResponsesRuneDetails from './model/GithubComSatstreamSsUtilsOrdServerResponsesRuneDetails';
import GithubComSatstreamSsUtilsOrdServerResponsesRuneListEntry from './model/GithubComSatstreamSsUtilsOrdServerResponsesRuneListEntry';
import GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse from './model/GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse2002 from './model/InlineResponse2002';
import Input from './model/Input';
import InscriptionData from './model/InscriptionData';
import InscriptionResponse from './model/InscriptionResponse';
import JoinPSBTsRequest from './model/JoinPSBTsRequest';
import JoinPSBTsResponse from './model/JoinPSBTsResponse';
import LatestInscriptionsResponse from './model/LatestInscriptionsResponse';
import MempoolAncestorsData from './model/MempoolAncestorsData';
import MempoolDescendantsData from './model/MempoolDescendantsData';
import MempoolEntry from './model/MempoolEntry';
import MempoolFees from './model/MempoolFees';
import MempoolInfo from './model/MempoolInfo';
import MempoolSequence from './model/MempoolSequence';
import MiningInfo from './model/MiningInfo';
import Output from './model/Output';
import OutputResponse from './model/OutputResponse';
import PSBTAnalysis from './model/PSBTAnalysis';
import PSBTBip32Deriv from './model/PSBTBip32Deriv';
import PSBTInputAnalysis from './model/PSBTInputAnalysis';
import PSBTMissingData from './model/PSBTMissingData';
import PSBTWitnessUtxo from './model/PSBTWitnessUtxo';
import PrevOut from './model/PrevOut';
import RawFeeEstimate from './model/RawFeeEstimate';
import RawMempoolData from './model/RawMempoolData';
import RawTx1 from './model/RawTx1';
import RawTx2 from './model/RawTx2';
import RuneResponse from './model/RuneResponse';
import RuneTerms from './model/RuneTerms';
import RunesBalance from './model/RunesBalance';
import RunestoneData from './model/RunestoneData';
import SatoshiResponse from './model/SatoshiResponse';
import Script from './model/Script';
import ScriptPubKey from './model/ScriptPubKey';
import ScriptSig from './model/ScriptSig';
import SegwitDetails from './model/SegwitDetails';
import SendRawTransactionResponse from './model/SendRawTransactionResponse';
import SmartFeeEstimate from './model/SmartFeeEstimate';
import StatusResponse from './model/StatusResponse';
import TestMempoolAcceptRequest from './model/TestMempoolAcceptRequest';
import TestMempoolAcceptResponse from './model/TestMempoolAcceptResponse';
import TestMempoolAcceptResult from './model/TestMempoolAcceptResult';
import TestMempoolFees from './model/TestMempoolFees';
import Transaction from './model/Transaction';
import TransactionCombineRawTransactionRequest from './model/TransactionCombineRawTransactionRequest';
import TransactionConvertToPSBTRequest from './model/TransactionConvertToPSBTRequest';
import TransactionCreateRawTxInput from './model/TransactionCreateRawTxInput';
import TransactionCreateRawTxRequest from './model/TransactionCreateRawTxRequest';
import TransactionGetTxOutProofRequest from './model/TransactionGetTxOutProofRequest';
import TransactionGetTxOutRequest from './model/TransactionGetTxOutRequest';
import TransactionGetTxOutSetInfoRequest from './model/TransactionGetTxOutSetInfoRequest';
import TransactionGetTxSpendingPrevoutRequest from './model/TransactionGetTxSpendingPrevoutRequest';
import TransactionSendRawTransactionRequest from './model/TransactionSendRawTransactionRequest';
import TransactionVerifyTxOutProofRequest from './model/TransactionVerifyTxOutProofRequest';
import TxOut from './model/TxOut';
import TxSpendingPrevoutInput from './model/TxSpendingPrevoutInput';
import TxSpendingPrevoutResult from './model/TxSpendingPrevoutResult';
import TxVin1 from './model/TxVin1';
import TxVin2 from './model/TxVin2';
import UTXOBlockInfo from './model/UTXOBlockInfo';
import UTXOSetInfo from './model/UTXOSetInfo';
import UTXOUnspendables from './model/UTXOUnspendables';
import UnknownFields from './model/UnknownFields';
import UtilsResponseEnvelope from './model/UtilsResponseEnvelope';
import ValidateAddressResponse from './model/ValidateAddressResponse';
import ValidateAddressResult from './model/ValidateAddressResult';
import VerifyTxOutProofResponse from './model/VerifyTxOutProofResponse';
import Vout from './model/Vout';
import AddressesApi from './api/AddressesApi';
import BlocksApi from './api/BlocksApi';
import FeesApi from './api/FeesApi';
import InscriptionsApi from './api/InscriptionsApi';
import MempoolApi from './api/MempoolApi';
import MiningApi from './api/MiningApi';
import NetworkApi from './api/NetworkApi';
import OutputsApi from './api/OutputsApi';
import PSBTsApi from './api/PSBTsApi';
import RunesApi from './api/RunesApi';
import SatoshisApi from './api/SatoshisApi';
import ScriptsApi from './api/ScriptsApi';
import StatusApi from './api/StatusApi';
import TransactionsApi from './api/TransactionsApi';

/**
* Satstream JavaScript SDK.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SatstreamJavascriptSdk = require('index'); // See note below*.
* var xxxSvc = new SatstreamJavascriptSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SatstreamJavascriptSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SatstreamJavascriptSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SatstreamJavascriptSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.26
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddressResponse model constructor.
     * @property {module:model/AddressResponse}
     */
    AddressResponse,

    /**
     * The AddressRuneDelta model constructor.
     * @property {module:model/AddressRuneDelta}
     */
    AddressRuneDelta,

    /**
     * The AllOfBlockVin2ScriptSig model constructor.
     * @property {module:model/AllOfBlockVin2ScriptSig}
     */
    AllOfBlockVin2ScriptSig,

    /**
     * The AllOfBlockVin3Prevout model constructor.
     * @property {module:model/AllOfBlockVin3Prevout}
     */
    AllOfBlockVin3Prevout,

    /**
     * The AllOfDecodedPSBTInputFinalScriptsig model constructor.
     * @property {module:model/AllOfDecodedPSBTInputFinalScriptsig}
     */
    AllOfDecodedPSBTInputFinalScriptsig,

    /**
     * The AllOfDecodedPSBTInputNonWitnessUtxo model constructor.
     * @property {module:model/AllOfDecodedPSBTInputNonWitnessUtxo}
     */
    AllOfDecodedPSBTInputNonWitnessUtxo,

    /**
     * The AllOfDecodedPSBTInputRedeemScript model constructor.
     * @property {module:model/AllOfDecodedPSBTInputRedeemScript}
     */
    AllOfDecodedPSBTInputRedeemScript,

    /**
     * The AllOfDecodedPSBTInputUnknown model constructor.
     * @property {module:model/AllOfDecodedPSBTInputUnknown}
     */
    AllOfDecodedPSBTInputUnknown,

    /**
     * The AllOfDecodedPSBTInputWitnessScript model constructor.
     * @property {module:model/AllOfDecodedPSBTInputWitnessScript}
     */
    AllOfDecodedPSBTInputWitnessScript,

    /**
     * The AllOfDecodedPSBTInputWitnessUtxo model constructor.
     * @property {module:model/AllOfDecodedPSBTInputWitnessUtxo}
     */
    AllOfDecodedPSBTInputWitnessUtxo,

    /**
     * The AllOfDecodedPSBTOutputRedeemScript model constructor.
     * @property {module:model/AllOfDecodedPSBTOutputRedeemScript}
     */
    AllOfDecodedPSBTOutputRedeemScript,

    /**
     * The AllOfDecodedPSBTOutputUnknown model constructor.
     * @property {module:model/AllOfDecodedPSBTOutputUnknown}
     */
    AllOfDecodedPSBTOutputUnknown,

    /**
     * The AllOfDecodedPSBTOutputWitnessScript model constructor.
     * @property {module:model/AllOfDecodedPSBTOutputWitnessScript}
     */
    AllOfDecodedPSBTOutputWitnessScript,

    /**
     * The AllOfDecodedPSBTTx model constructor.
     * @property {module:model/AllOfDecodedPSBTTx}
     */
    AllOfDecodedPSBTTx,

    /**
     * The AllOfDecodedPSBTUnknown model constructor.
     * @property {module:model/AllOfDecodedPSBTUnknown}
     */
    AllOfDecodedPSBTUnknown,

    /**
     * The AllOfDecodedScriptSegwit model constructor.
     * @property {module:model/AllOfDecodedScriptSegwit}
     */
    AllOfDecodedScriptSegwit,

    /**
     * The AllOfFeeHorizonEstimateFail model constructor.
     * @property {module:model/AllOfFeeHorizonEstimateFail}
     */
    AllOfFeeHorizonEstimateFail,

    /**
     * The AllOfFeeHorizonEstimatePass model constructor.
     * @property {module:model/AllOfFeeHorizonEstimatePass}
     */
    AllOfFeeHorizonEstimatePass,

    /**
     * The AllOfMempoolEntryFees model constructor.
     * @property {module:model/AllOfMempoolEntryFees}
     */
    AllOfMempoolEntryFees,

    /**
     * The AllOfPSBTWitnessUtxoScriptPubKey model constructor.
     * @property {module:model/AllOfPSBTWitnessUtxoScriptPubKey}
     */
    AllOfPSBTWitnessUtxoScriptPubKey,

    /**
     * The AllOfRawFeeEstimateMedium model constructor.
     * @property {module:model/AllOfRawFeeEstimateMedium}
     */
    AllOfRawFeeEstimateMedium,

    /**
     * The AllOfRawFeeEstimateModelLong model constructor.
     * @property {module:model/AllOfRawFeeEstimateModelLong}
     */
    AllOfRawFeeEstimateModelLong,

    /**
     * The AllOfRawFeeEstimateModelShort model constructor.
     * @property {module:model/AllOfRawFeeEstimateModelShort}
     */
    AllOfRawFeeEstimateModelShort,

    /**
     * The AllOfRawMempoolDataSequence model constructor.
     * @property {module:model/AllOfRawMempoolDataSequence}
     */
    AllOfRawMempoolDataSequence,

    /**
     * The AllOfTestMempoolAcceptResultFees model constructor.
     * @property {module:model/AllOfTestMempoolAcceptResultFees}
     */
    AllOfTestMempoolAcceptResultFees,

    /**
     * The AllOfTxOutScriptPubKey model constructor.
     * @property {module:model/AllOfTxOutScriptPubKey}
     */
    AllOfTxOutScriptPubKey,

    /**
     * The AllOfUTXOBlockInfoUnspendables model constructor.
     * @property {module:model/AllOfUTXOBlockInfoUnspendables}
     */
    AllOfUTXOBlockInfoUnspendables,

    /**
     * The AllOfUTXOSetInfoBlockInfo model constructor.
     * @property {module:model/AllOfUTXOSetInfoBlockInfo}
     */
    AllOfUTXOSetInfoBlockInfo,

    /**
     * The AnalyzePSBTRequest model constructor.
     * @property {module:model/AnalyzePSBTRequest}
     */
    AnalyzePSBTRequest,

    /**
     * The AnalyzePSBTResponse model constructor.
     * @property {module:model/AnalyzePSBTResponse}
     */
    AnalyzePSBTResponse,

    /**
     * The BigInt model constructor.
     * @property {module:model/BigInt}
     */
    BigInt,

    /**
     * The Bip32Deriv model constructor.
     * @property {module:model/Bip32Deriv}
     */
    Bip32Deriv,

    /**
     * The Block1 model constructor.
     * @property {module:model/Block1}
     */
    Block1,

    /**
     * The Block2 model constructor.
     * @property {module:model/Block2}
     */
    Block2,

    /**
     * The Block3 model constructor.
     * @property {module:model/Block3}
     */
    Block3,

    /**
     * The BlockResponse model constructor.
     * @property {module:model/BlockResponse}
     */
    BlockResponse,

    /**
     * The BlockStats model constructor.
     * @property {module:model/BlockStats}
     */
    BlockStats,

    /**
     * The BlockVin2 model constructor.
     * @property {module:model/BlockVin2}
     */
    BlockVin2,

    /**
     * The BlockVin3 model constructor.
     * @property {module:model/BlockVin3}
     */
    BlockVin3,

    /**
     * The BlockchainInfo model constructor.
     * @property {module:model/BlockchainInfo}
     */
    BlockchainInfo,

    /**
     * The BlocksResponse model constructor.
     * @property {module:model/BlocksResponse}
     */
    BlocksResponse,

    /**
     * The BtcTx2 model constructor.
     * @property {module:model/BtcTx2}
     */
    BtcTx2,

    /**
     * The BtcTx3 model constructor.
     * @property {module:model/BtcTx3}
     */
    BtcTx3,

    /**
     * The ChainTxStats model constructor.
     * @property {module:model/ChainTxStats}
     */
    ChainTxStats,

    /**
     * The CombinePSBTRequest model constructor.
     * @property {module:model/CombinePSBTRequest}
     */
    CombinePSBTRequest,

    /**
     * The CombinePSBTResponse model constructor.
     * @property {module:model/CombinePSBTResponse}
     */
    CombinePSBTResponse,

    /**
     * The CombineRawTransactionResponse model constructor.
     * @property {module:model/CombineRawTransactionResponse}
     */
    CombineRawTransactionResponse,

    /**
     * The ConvertToPSBTResponse model constructor.
     * @property {module:model/ConvertToPSBTResponse}
     */
    ConvertToPSBTResponse,

    /**
     * The CreatePSBTInput model constructor.
     * @property {module:model/CreatePSBTInput}
     */
    CreatePSBTInput,

    /**
     * The CreatePSBTRequest model constructor.
     * @property {module:model/CreatePSBTRequest}
     */
    CreatePSBTRequest,

    /**
     * The CreatePSBTResponse model constructor.
     * @property {module:model/CreatePSBTResponse}
     */
    CreatePSBTResponse,

    /**
     * The CreateRawTransactionResponse model constructor.
     * @property {module:model/CreateRawTransactionResponse}
     */
    CreateRawTransactionResponse,

    /**
     * The DecodePSBTRequest model constructor.
     * @property {module:model/DecodePSBTRequest}
     */
    DecodePSBTRequest,

    /**
     * The DecodePSBTResponse model constructor.
     * @property {module:model/DecodePSBTResponse}
     */
    DecodePSBTResponse,

    /**
     * The DecodeResponse model constructor.
     * @property {module:model/DecodeResponse}
     */
    DecodeResponse,

    /**
     * The DecodeScriptRequest model constructor.
     * @property {module:model/DecodeScriptRequest}
     */
    DecodeScriptRequest,

    /**
     * The DecodeScriptResponse model constructor.
     * @property {module:model/DecodeScriptResponse}
     */
    DecodeScriptResponse,

    /**
     * The DecodeTransactionResponse model constructor.
     * @property {module:model/DecodeTransactionResponse}
     */
    DecodeTransactionResponse,

    /**
     * The DecodedInscription model constructor.
     * @property {module:model/DecodedInscription}
     */
    DecodedInscription,

    /**
     * The DecodedPSBT model constructor.
     * @property {module:model/DecodedPSBT}
     */
    DecodedPSBT,

    /**
     * The DecodedPSBTInput model constructor.
     * @property {module:model/DecodedPSBTInput}
     */
    DecodedPSBTInput,

    /**
     * The DecodedPSBTOutput model constructor.
     * @property {module:model/DecodedPSBTOutput}
     */
    DecodedPSBTOutput,

    /**
     * The DecodedScript model constructor.
     * @property {module:model/DecodedScript}
     */
    DecodedScript,

    /**
     * The EstimateRawFeeRequest model constructor.
     * @property {module:model/EstimateRawFeeRequest}
     */
    EstimateRawFeeRequest,

    /**
     * The EstimateRawFeeResponse model constructor.
     * @property {module:model/EstimateRawFeeResponse}
     */
    EstimateRawFeeResponse,

    /**
     * The EstimateSmartFeeRequest model constructor.
     * @property {module:model/EstimateSmartFeeRequest}
     */
    EstimateSmartFeeRequest,

    /**
     * The EstimateSmartFeeResponse model constructor.
     * @property {module:model/EstimateSmartFeeResponse}
     */
    EstimateSmartFeeResponse,

    /**
     * The FeeHorizonEstimate model constructor.
     * @property {module:model/FeeHorizonEstimate}
     */
    FeeHorizonEstimate,

    /**
     * The FeeRange model constructor.
     * @property {module:model/FeeRange}
     */
    FeeRange,

    /**
     * The FetchInscriptionsResponse model constructor.
     * @property {module:model/FetchInscriptionsResponse}
     */
    FetchInscriptionsResponse,

    /**
     * The GetAddressDeltasResponse model constructor.
     * @property {module:model/GetAddressDeltasResponse}
     */
    GetAddressDeltasResponse,

    /**
     * The GetAddressResponse model constructor.
     * @property {module:model/GetAddressResponse}
     */
    GetAddressResponse,

    /**
     * The GetAddressRuneDeltasResponse model constructor.
     * @property {module:model/GetAddressRuneDeltasResponse}
     */
    GetAddressRuneDeltasResponse,

    /**
     * The GetAddressUTXOsResponse model constructor.
     * @property {module:model/GetAddressUTXOsResponse}
     */
    GetAddressUTXOsResponse,

    /**
     * The GetBlockCountResponse model constructor.
     * @property {module:model/GetBlockCountResponse}
     */
    GetBlockCountResponse,

    /**
     * The GetBlockDecodedResponse model constructor.
     * @property {module:model/GetBlockDecodedResponse}
     */
    GetBlockDecodedResponse,

    /**
     * The GetBlockHashByHeightResponse model constructor.
     * @property {module:model/GetBlockHashByHeightResponse}
     */
    GetBlockHashByHeightResponse,

    /**
     * The GetBlockHexResponse model constructor.
     * @property {module:model/GetBlockHexResponse}
     */
    GetBlockHexResponse,

    /**
     * The GetBlockInscriptionsResponse model constructor.
     * @property {module:model/GetBlockInscriptionsResponse}
     */
    GetBlockInscriptionsResponse,

    /**
     * The GetBlockPrevoutResponse model constructor.
     * @property {module:model/GetBlockPrevoutResponse}
     */
    GetBlockPrevoutResponse,

    /**
     * The GetBlockResponse model constructor.
     * @property {module:model/GetBlockResponse}
     */
    GetBlockResponse,

    /**
     * The GetBlockStatsRequest model constructor.
     * @property {module:model/GetBlockStatsRequest}
     */
    GetBlockStatsRequest,

    /**
     * The GetBlockStatsResponse model constructor.
     * @property {module:model/GetBlockStatsResponse}
     */
    GetBlockStatsResponse,

    /**
     * The GetBlockSummaryResponse model constructor.
     * @property {module:model/GetBlockSummaryResponse}
     */
    GetBlockSummaryResponse,

    /**
     * The GetBlockchainInfoResponse model constructor.
     * @property {module:model/GetBlockchainInfoResponse}
     */
    GetBlockchainInfoResponse,

    /**
     * The GetBlocksResponse model constructor.
     * @property {module:model/GetBlocksResponse}
     */
    GetBlocksResponse,

    /**
     * The GetChainTxStatsRequest model constructor.
     * @property {module:model/GetChainTxStatsRequest}
     */
    GetChainTxStatsRequest,

    /**
     * The GetChainTxStatsResponse model constructor.
     * @property {module:model/GetChainTxStatsResponse}
     */
    GetChainTxStatsResponse,

    /**
     * The GetDifficultyResponse model constructor.
     * @property {module:model/GetDifficultyResponse}
     */
    GetDifficultyResponse,

    /**
     * The GetInscriptionChildResponse model constructor.
     * @property {module:model/GetInscriptionChildResponse}
     */
    GetInscriptionChildResponse,

    /**
     * The GetInscriptionResponse model constructor.
     * @property {module:model/GetInscriptionResponse}
     */
    GetInscriptionResponse,

    /**
     * The GetLatestBlockHashResponse model constructor.
     * @property {module:model/GetLatestBlockHashResponse}
     */
    GetLatestBlockHashResponse,

    /**
     * The GetLatestBlockHeightResponse model constructor.
     * @property {module:model/GetLatestBlockHeightResponse}
     */
    GetLatestBlockHeightResponse,

    /**
     * The GetLatestBlockTimeResponse model constructor.
     * @property {module:model/GetLatestBlockTimeResponse}
     */
    GetLatestBlockTimeResponse,

    /**
     * The GetLatestInscriptionsResponse model constructor.
     * @property {module:model/GetLatestInscriptionsResponse}
     */
    GetLatestInscriptionsResponse,

    /**
     * The GetLatestRunesResponse model constructor.
     * @property {module:model/GetLatestRunesResponse}
     */
    GetLatestRunesResponse,

    /**
     * The GetMempoolAncestorsRequest model constructor.
     * @property {module:model/GetMempoolAncestorsRequest}
     */
    GetMempoolAncestorsRequest,

    /**
     * The GetMempoolAncestorsResponse model constructor.
     * @property {module:model/GetMempoolAncestorsResponse}
     */
    GetMempoolAncestorsResponse,

    /**
     * The GetMempoolDescendantsRequest model constructor.
     * @property {module:model/GetMempoolDescendantsRequest}
     */
    GetMempoolDescendantsRequest,

    /**
     * The GetMempoolDescendantsResponse model constructor.
     * @property {module:model/GetMempoolDescendantsResponse}
     */
    GetMempoolDescendantsResponse,

    /**
     * The GetMempoolInfoResponse model constructor.
     * @property {module:model/GetMempoolInfoResponse}
     */
    GetMempoolInfoResponse,

    /**
     * The GetMiningInfoResponse model constructor.
     * @property {module:model/GetMiningInfoResponse}
     */
    GetMiningInfoResponse,

    /**
     * The GetNetworkHashPSRequest model constructor.
     * @property {module:model/GetNetworkHashPSRequest}
     */
    GetNetworkHashPSRequest,

    /**
     * The GetNetworkHashPSResponse model constructor.
     * @property {module:model/GetNetworkHashPSResponse}
     */
    GetNetworkHashPSResponse,

    /**
     * The GetRawMempoolRequest model constructor.
     * @property {module:model/GetRawMempoolRequest}
     */
    GetRawMempoolRequest,

    /**
     * The GetRawMempoolResponse model constructor.
     * @property {module:model/GetRawMempoolResponse}
     */
    GetRawMempoolResponse,

    /**
     * The GetRawTransactionDecodeResponse model constructor.
     * @property {module:model/GetRawTransactionDecodeResponse}
     */
    GetRawTransactionDecodeResponse,

    /**
     * The GetRawTransactionHexResponse model constructor.
     * @property {module:model/GetRawTransactionHexResponse}
     */
    GetRawTransactionHexResponse,

    /**
     * The GetRawTransactionPrevoutResponse model constructor.
     * @property {module:model/GetRawTransactionPrevoutResponse}
     */
    GetRawTransactionPrevoutResponse,

    /**
     * The GetRuneResponse model constructor.
     * @property {module:model/GetRuneResponse}
     */
    GetRuneResponse,

    /**
     * The GetSatoshiResponse model constructor.
     * @property {module:model/GetSatoshiResponse}
     */
    GetSatoshiResponse,

    /**
     * The GetStatusResponse model constructor.
     * @property {module:model/GetStatusResponse}
     */
    GetStatusResponse,

    /**
     * The GetTxOutProofResponse model constructor.
     * @property {module:model/GetTxOutProofResponse}
     */
    GetTxOutProofResponse,

    /**
     * The GetTxOutResponse model constructor.
     * @property {module:model/GetTxOutResponse}
     */
    GetTxOutResponse,

    /**
     * The GetTxSpendingPrevoutResponse model constructor.
     * @property {module:model/GetTxSpendingPrevoutResponse}
     */
    GetTxSpendingPrevoutResponse,

    /**
     * The GithubComSatstreamSsUtilsDatabaseAddressDelta model constructor.
     * @property {module:model/GithubComSatstreamSsUtilsDatabaseAddressDelta}
     */
    GithubComSatstreamSsUtilsDatabaseAddressDelta,

    /**
     * The GithubComSatstreamSsUtilsOrdServerResponsesRuneDetails model constructor.
     * @property {module:model/GithubComSatstreamSsUtilsOrdServerResponsesRuneDetails}
     */
    GithubComSatstreamSsUtilsOrdServerResponsesRuneDetails,

    /**
     * The GithubComSatstreamSsUtilsOrdServerResponsesRuneListEntry model constructor.
     * @property {module:model/GithubComSatstreamSsUtilsOrdServerResponsesRuneListEntry}
     */
    GithubComSatstreamSsUtilsOrdServerResponsesRuneListEntry,

    /**
     * The GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse model constructor.
     * @property {module:model/GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse}
     */
    GithubComSatstreamSsUtilsOrdServerResponsesRunesListResponse,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The Input model constructor.
     * @property {module:model/Input}
     */
    Input,

    /**
     * The InscriptionData model constructor.
     * @property {module:model/InscriptionData}
     */
    InscriptionData,

    /**
     * The InscriptionResponse model constructor.
     * @property {module:model/InscriptionResponse}
     */
    InscriptionResponse,

    /**
     * The JoinPSBTsRequest model constructor.
     * @property {module:model/JoinPSBTsRequest}
     */
    JoinPSBTsRequest,

    /**
     * The JoinPSBTsResponse model constructor.
     * @property {module:model/JoinPSBTsResponse}
     */
    JoinPSBTsResponse,

    /**
     * The LatestInscriptionsResponse model constructor.
     * @property {module:model/LatestInscriptionsResponse}
     */
    LatestInscriptionsResponse,

    /**
     * The MempoolAncestorsData model constructor.
     * @property {module:model/MempoolAncestorsData}
     */
    MempoolAncestorsData,

    /**
     * The MempoolDescendantsData model constructor.
     * @property {module:model/MempoolDescendantsData}
     */
    MempoolDescendantsData,

    /**
     * The MempoolEntry model constructor.
     * @property {module:model/MempoolEntry}
     */
    MempoolEntry,

    /**
     * The MempoolFees model constructor.
     * @property {module:model/MempoolFees}
     */
    MempoolFees,

    /**
     * The MempoolInfo model constructor.
     * @property {module:model/MempoolInfo}
     */
    MempoolInfo,

    /**
     * The MempoolSequence model constructor.
     * @property {module:model/MempoolSequence}
     */
    MempoolSequence,

    /**
     * The MiningInfo model constructor.
     * @property {module:model/MiningInfo}
     */
    MiningInfo,

    /**
     * The Output model constructor.
     * @property {module:model/Output}
     */
    Output,

    /**
     * The OutputResponse model constructor.
     * @property {module:model/OutputResponse}
     */
    OutputResponse,

    /**
     * The PSBTAnalysis model constructor.
     * @property {module:model/PSBTAnalysis}
     */
    PSBTAnalysis,

    /**
     * The PSBTBip32Deriv model constructor.
     * @property {module:model/PSBTBip32Deriv}
     */
    PSBTBip32Deriv,

    /**
     * The PSBTInputAnalysis model constructor.
     * @property {module:model/PSBTInputAnalysis}
     */
    PSBTInputAnalysis,

    /**
     * The PSBTMissingData model constructor.
     * @property {module:model/PSBTMissingData}
     */
    PSBTMissingData,

    /**
     * The PSBTWitnessUtxo model constructor.
     * @property {module:model/PSBTWitnessUtxo}
     */
    PSBTWitnessUtxo,

    /**
     * The PrevOut model constructor.
     * @property {module:model/PrevOut}
     */
    PrevOut,

    /**
     * The RawFeeEstimate model constructor.
     * @property {module:model/RawFeeEstimate}
     */
    RawFeeEstimate,

    /**
     * The RawMempoolData model constructor.
     * @property {module:model/RawMempoolData}
     */
    RawMempoolData,

    /**
     * The RawTx1 model constructor.
     * @property {module:model/RawTx1}
     */
    RawTx1,

    /**
     * The RawTx2 model constructor.
     * @property {module:model/RawTx2}
     */
    RawTx2,

    /**
     * The RuneResponse model constructor.
     * @property {module:model/RuneResponse}
     */
    RuneResponse,

    /**
     * The RuneTerms model constructor.
     * @property {module:model/RuneTerms}
     */
    RuneTerms,

    /**
     * The RunesBalance model constructor.
     * @property {module:model/RunesBalance}
     */
    RunesBalance,

    /**
     * The RunestoneData model constructor.
     * @property {module:model/RunestoneData}
     */
    RunestoneData,

    /**
     * The SatoshiResponse model constructor.
     * @property {module:model/SatoshiResponse}
     */
    SatoshiResponse,

    /**
     * The Script model constructor.
     * @property {module:model/Script}
     */
    Script,

    /**
     * The ScriptPubKey model constructor.
     * @property {module:model/ScriptPubKey}
     */
    ScriptPubKey,

    /**
     * The ScriptSig model constructor.
     * @property {module:model/ScriptSig}
     */
    ScriptSig,

    /**
     * The SegwitDetails model constructor.
     * @property {module:model/SegwitDetails}
     */
    SegwitDetails,

    /**
     * The SendRawTransactionResponse model constructor.
     * @property {module:model/SendRawTransactionResponse}
     */
    SendRawTransactionResponse,

    /**
     * The SmartFeeEstimate model constructor.
     * @property {module:model/SmartFeeEstimate}
     */
    SmartFeeEstimate,

    /**
     * The StatusResponse model constructor.
     * @property {module:model/StatusResponse}
     */
    StatusResponse,

    /**
     * The TestMempoolAcceptRequest model constructor.
     * @property {module:model/TestMempoolAcceptRequest}
     */
    TestMempoolAcceptRequest,

    /**
     * The TestMempoolAcceptResponse model constructor.
     * @property {module:model/TestMempoolAcceptResponse}
     */
    TestMempoolAcceptResponse,

    /**
     * The TestMempoolAcceptResult model constructor.
     * @property {module:model/TestMempoolAcceptResult}
     */
    TestMempoolAcceptResult,

    /**
     * The TestMempoolFees model constructor.
     * @property {module:model/TestMempoolFees}
     */
    TestMempoolFees,

    /**
     * The Transaction model constructor.
     * @property {module:model/Transaction}
     */
    Transaction,

    /**
     * The TransactionCombineRawTransactionRequest model constructor.
     * @property {module:model/TransactionCombineRawTransactionRequest}
     */
    TransactionCombineRawTransactionRequest,

    /**
     * The TransactionConvertToPSBTRequest model constructor.
     * @property {module:model/TransactionConvertToPSBTRequest}
     */
    TransactionConvertToPSBTRequest,

    /**
     * The TransactionCreateRawTxInput model constructor.
     * @property {module:model/TransactionCreateRawTxInput}
     */
    TransactionCreateRawTxInput,

    /**
     * The TransactionCreateRawTxRequest model constructor.
     * @property {module:model/TransactionCreateRawTxRequest}
     */
    TransactionCreateRawTxRequest,

    /**
     * The TransactionGetTxOutProofRequest model constructor.
     * @property {module:model/TransactionGetTxOutProofRequest}
     */
    TransactionGetTxOutProofRequest,

    /**
     * The TransactionGetTxOutRequest model constructor.
     * @property {module:model/TransactionGetTxOutRequest}
     */
    TransactionGetTxOutRequest,

    /**
     * The TransactionGetTxOutSetInfoRequest model constructor.
     * @property {module:model/TransactionGetTxOutSetInfoRequest}
     */
    TransactionGetTxOutSetInfoRequest,

    /**
     * The TransactionGetTxSpendingPrevoutRequest model constructor.
     * @property {module:model/TransactionGetTxSpendingPrevoutRequest}
     */
    TransactionGetTxSpendingPrevoutRequest,

    /**
     * The TransactionSendRawTransactionRequest model constructor.
     * @property {module:model/TransactionSendRawTransactionRequest}
     */
    TransactionSendRawTransactionRequest,

    /**
     * The TransactionVerifyTxOutProofRequest model constructor.
     * @property {module:model/TransactionVerifyTxOutProofRequest}
     */
    TransactionVerifyTxOutProofRequest,

    /**
     * The TxOut model constructor.
     * @property {module:model/TxOut}
     */
    TxOut,

    /**
     * The TxSpendingPrevoutInput model constructor.
     * @property {module:model/TxSpendingPrevoutInput}
     */
    TxSpendingPrevoutInput,

    /**
     * The TxSpendingPrevoutResult model constructor.
     * @property {module:model/TxSpendingPrevoutResult}
     */
    TxSpendingPrevoutResult,

    /**
     * The TxVin1 model constructor.
     * @property {module:model/TxVin1}
     */
    TxVin1,

    /**
     * The TxVin2 model constructor.
     * @property {module:model/TxVin2}
     */
    TxVin2,

    /**
     * The UTXOBlockInfo model constructor.
     * @property {module:model/UTXOBlockInfo}
     */
    UTXOBlockInfo,

    /**
     * The UTXOSetInfo model constructor.
     * @property {module:model/UTXOSetInfo}
     */
    UTXOSetInfo,

    /**
     * The UTXOUnspendables model constructor.
     * @property {module:model/UTXOUnspendables}
     */
    UTXOUnspendables,

    /**
     * The UnknownFields model constructor.
     * @property {module:model/UnknownFields}
     */
    UnknownFields,

    /**
     * The UtilsResponseEnvelope model constructor.
     * @property {module:model/UtilsResponseEnvelope}
     */
    UtilsResponseEnvelope,

    /**
     * The ValidateAddressResponse model constructor.
     * @property {module:model/ValidateAddressResponse}
     */
    ValidateAddressResponse,

    /**
     * The ValidateAddressResult model constructor.
     * @property {module:model/ValidateAddressResult}
     */
    ValidateAddressResult,

    /**
     * The VerifyTxOutProofResponse model constructor.
     * @property {module:model/VerifyTxOutProofResponse}
     */
    VerifyTxOutProofResponse,

    /**
     * The Vout model constructor.
     * @property {module:model/Vout}
     */
    Vout,

    /**
    * The AddressesApi service constructor.
    * @property {module:api/AddressesApi}
    */
    AddressesApi,

    /**
    * The BlocksApi service constructor.
    * @property {module:api/BlocksApi}
    */
    BlocksApi,

    /**
    * The FeesApi service constructor.
    * @property {module:api/FeesApi}
    */
    FeesApi,

    /**
    * The InscriptionsApi service constructor.
    * @property {module:api/InscriptionsApi}
    */
    InscriptionsApi,

    /**
    * The MempoolApi service constructor.
    * @property {module:api/MempoolApi}
    */
    MempoolApi,

    /**
    * The MiningApi service constructor.
    * @property {module:api/MiningApi}
    */
    MiningApi,

    /**
    * The NetworkApi service constructor.
    * @property {module:api/NetworkApi}
    */
    NetworkApi,

    /**
    * The OutputsApi service constructor.
    * @property {module:api/OutputsApi}
    */
    OutputsApi,

    /**
    * The PSBTsApi service constructor.
    * @property {module:api/PSBTsApi}
    */
    PSBTsApi,

    /**
    * The RunesApi service constructor.
    * @property {module:api/RunesApi}
    */
    RunesApi,

    /**
    * The SatoshisApi service constructor.
    * @property {module:api/SatoshisApi}
    */
    SatoshisApi,

    /**
    * The ScriptsApi service constructor.
    * @property {module:api/ScriptsApi}
    */
    ScriptsApi,

    /**
    * The StatusApi service constructor.
    * @property {module:api/StatusApi}
    */
    StatusApi,

    /**
    * The TransactionsApi service constructor.
    * @property {module:api/TransactionsApi}
    */
    TransactionsApi
};
